### ISSUE TITLE
Lỗi Nettruyen, TruyenQQ không load được.

### ISSUE THREAD

**Issue by tradao2610** [JustaTama/Aidoku-VN-Sources#1]
2 web này hình như mới đổi URL gần đây nên không load được truyện từ source.

**Comment by JustaTama** [comment]
> 2 web này hình như mới đổi URL gần đây nên không load được truyện từ source.

Đã update. Thằng nettruyen này thay đổi domain liên tục, 1 tháng mà 2 3 lần đổi rồi.
![323797008_1192992301353094_8608323294965891255_n](https://user-images.githubusercontent.com/65128440/211141781-3cb003a2-ab81-4bea-9688-03d48968dd73.jpg)

**Comment by JustaTama** [comment]
fixed
