### ISSUE TITLE
TruyenQQ không load được chapter

### ISSUE THREAD

**Issue by tradao2610** [JustaTama/Aidoku-VN-Sources#2]
Có vẻ như source này có mỗi tôi dùng thì phải, ước viết dev để làm source tự fix lol

**Comment by tradao2610** [comment]
Thực ra là không load được thêm 
[https://streamable.com/yw4n4e](url)

**Comment by JustaTama** [comment]
> Có vẻ như nguồn này có mỗi tôi dùng thì phải, ước dev viết để làm nguồn tự fix lol

TruyenQQ vừa đổi domain nên thế với cả thấy kco phản hồi với ít ai dùng nên cũng lười vào check.

**Comment by JustaTama** [comment]
fixed
